### ISSUE TITLE
Stops working when Japanese/Chinese characters are in the stream's title.

### ISSUE THREAD

**Issue by kosempaxzo** [ntfwc/twitch_desktop_notification_system#1]
Just that.

**Comment by ntfwc** [comment]
Confirmed on Windows 7. 
Does not affect Ubuntu 12.04.

**Comment by ntfwc** [comment]
Turns out it was an issue with how Python "print" interacts with cmd on Windows. It assumes non-unicode text, so there must be an explicit encoding. 

But the unicode still doesn't render properly in the command line window, at least on my locale. An alternate command line shell with full unicode support should display it correctly, if needed. 

Note that this doesn't affect the notification pop-ups themselves, which should always render the text perfectly.
